name: Sync Local Folder with S3

on:
  push:
    branches:
      - master

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # v3 is the latest stable

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Upload files to S3
        run: |
          aws s3 sync papulal s3://covidcicds3 --exclude ".git/" --exclude ".github/
          aws s3 cp model.pkl s3://${{ secrets.S3_BUCKET_NAME }}/model.pkl
          aws s3 cp covid_toy.csv s3://${{ secrets.S3_BUCKET_NAME }}/covid_toy.csv